os: osx
osx_image: xcode11.3
language: objective-c

before_cache:
  - brew cleanup

cache:
  bundler: true
  directories:
    - $HOME/Library/Caches/Homebrew

after_install:
  - brew install swiftlint

script:
  - bundle exec fastlane run swiftlint strict:"true"
  - bundle exec fastlane gym --skip_codesigning --skip_archive --skip_package_ipa
